### ISSUE TITLE
[Bug Report] npm镜像500错误

### ISSUE THREAD

**Issue by ChongChengAC** [ZJUSCT/mirror-issues#26]
安装mermaid-cli时报错：
```
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://mirrors.zju.edu.cn/npm/chalk
```

完整的错误日志：
```
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.8.0
2 info using node@v20.4.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/home/qiu/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:setEnvs Completed in 0ms
15 timing config:load Completed in 7ms
16 timing npm:load:configload Completed in 7ms
17 timing config:load:flatten Completed in 2ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install mermaid-cli-10.2.4.tgz
21 verbose argv "install" "--global" "--omit" "dev" "--prefix" "/home/qiu/.cache/yay/mermaid-cli/pkg/mermaid-cli/usr" "mermaid-cli-10.2.4.tgz"
22 timing npm:load:setTitle Completed in 1ms
23 timing npm:load:display Completed in 0ms
24 verbose logfile logs-max:10 dir:/home/qiu/.npm/_logs/2023-07-25T09_16_51_941Z-
25 verbose logfile /home/qiu/.npm/_logs/2023-07-25T09_16_51_941Z-debug-0.log
26 timing npm:load:logFile Completed in 8ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 29ms
30 timing config:load:flatten Completed in 1ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 8ms
35 timing idealTree:userRequests Completed in 76ms
36 silly idealTree buildDeps
37 silly fetch manifest @mermaid-js/mermaid-cli@file:../../../../src/mermaid-cli-10.2.4.tgz
38 silly placeDep ROOT @mermaid-js/mermaid-cli@10.2.4 OK for:  want: file:../../../../src/mermaid-cli-10.2.4.tgz
39 silly fetch manifest chalk@^5.0.1
40 silly fetch manifest commander@^10.0.0
41 silly fetch manifest puppeteer@^19.0.0
42 http fetch GET 500 https://mirrors.zju.edu.cn/npm/chalk 70570ms attempt #3 (cache skip)
43 http fetch GET 500 https://mirrors.zju.edu.cn/npm/puppeteer 70654ms attempt #3 (cache skip)
44 http fetch GET 500 https://mirrors.zju.edu.cn/npm/commander 70659ms attempt #3 (cache skip)
45 timing idealTree:#root Completed in 70716ms
46 silly placeDep node_modules/@mermaid-js/mermaid-cli chalk@ OK for: @mermaid-js/mermaid-cli@10.2.4 want: ^5.0.1
47 silly placeDep node_modules/@mermaid-js/mermaid-cli commander@ OK for: @mermaid-js/mermaid-cli@10.2.4 want: ^10.0.0
48 silly placeDep node_modules/@mermaid-js/mermaid-cli puppeteer@ OK for: @mermaid-js/mermaid-cli@10.2.4 want: ^19.0.0
49 timing idealTree:node_modules/@mermaid-js/mermaid-cli Completed in 4ms
50 timing idealTree:node_modules/@mermaid-js/mermaid-cli/node_modules/chalk Completed in 0ms
51 timing idealTree:node_modules/@mermaid-js/mermaid-cli/node_modules/commander Completed in 0ms
52 timing idealTree:node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer Completed in 0ms
53 timing idealTree:buildDeps Completed in 70722ms
54 timing idealTree:fixDepFlags Completed in 0ms
55 timing idealTree Completed in 70807ms
56 timing command:install Completed in 70815ms
57 verbose stack HttpErrorGeneral: 500 Internal Server Error - GET https://mirrors.zju.edu.cn/npm/chalk
57 verbose stack     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
57 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
57 verbose stack     at async RegistryFetcher.packument (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:87:19)
57 verbose stack     at async RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:23)
57 verbose stack     at async Promise.all (index 0)
57 verbose stack     at async #buildDepStep (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1034:5)
57 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
57 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
57 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:149:5)
57 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli-entry.js:61:5)
58 verbose statusCode 500
59 verbose pkgid chalk@^5.0.1
60 verbose cwd /home/qiu/.cache/yay/mermaid-cli/src
61 verbose Linux 6.4.3-1-MANJARO
62 verbose node v20.4.0
63 verbose npm  v9.8.0
64 error code E500
65 error 500 Internal Server Error - GET https://mirrors.zju.edu.cn/npm/chalk
66 verbose exit 1
67 timing npm Completed in 70966ms
68 verbose unfinished npm timer reify 1690276612092
69 verbose unfinished npm timer reify:loadTrees 1690276612095
70 verbose code 1
71 error A complete log of this run can be found in: /home/qiu/.npm/_logs/2023-07-25T09_16_51_941Z-debug-0.log
```

npm config:
```
; "user" config from /home/qiu/.npmrc

registry = "https://mirrors.zju.edu.cn/npm" 

; node bin location = /usr/bin/node
; node version = v20.4.0
; npm local prefix = /home/qiu
; npm version = 9.8.0
; cwd = /home/qiu
; HOME = /home/qiu
; Run `npm config ls -l` to show all defaults.
```

网络环境：校外

**Comment by determ1ne** [comment]
NPM 镜像已被移除，因此关闭此 issue
